<?php include('partials/header.phtml'); ?>

        <div class="container">
<?php foreach($tools as $toolName => $toolResult): ?>
<?php $hasOutput = (isset($toolResult->output) && $toolResult->output!==false && strlen($toolResult->output)>0) ?>
<?php if(!$hasOutput) { continue; } ?>
            <div id="tool-container-<?= $toolName ?>" class="well">
                <div id="tool-header-<?= $toolName ?>" class="row">
                    <div class="col-sm-10 col-xs-9">
                        <h2 class="text-primary nomargin-top" id="tool-title-<?= $toolName ?>">
                            <?php if($toolResult->success): ?><i class="glyphicon glyphicon-exclamation-sign text-danger"></i> <?php endif; ?><?= $toolName ?>
                        </h2>
                    </div>
                    <div class="col-sm-2 col-xs-3">
                        <a role="button" class="btn btn-warning pull-right" href="/">home</a>
                    </div>
                </div>
                <div id="tool-output-<?= $toolName ?>">
                    <?= $toolResult->output ?>
                </div>
            </div>
<?php endforeach; ?>
        </div>

<?php include('partials/footer.phtml'); ?>

